# Generated by Django 4.2.23 on 2025-07-06 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outbound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbound',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbounds', to='outbound.customer'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbounds', to='inventory.product'),
        ),
    ]
