# Generated by Django 4.2.23 on 2025-07-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='so_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
