# Generated by Django 4.2.23 on 2025-07-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='The change in quantity. Positive for inbound, negative for outbound.')),
                ('new_quantity', models.PositiveIntegerField(help_text='The new total quantity after the change.')),
                ('reason', models.CharField(blank=True, help_text="The reason for the stock change (e.g., 'Inbound Shipment', 'Sales Order', 'Manual Correction').", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit, must be unique.', max_length=100, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for easy filtering.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.')),
                ('category', models.CharField(blank=True, help_text='Product category.', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current quantity in stock.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Threshold for low stock alerts.')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the product is archived and not in active use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.product'),
        ),
    ]
