# Generated by Django 4.2.23 on 2025-07-02 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='The change in quantity. Positive for inbound, negative for outbound.')),
                ('new_quantity', models.PositiveIntegerField(help_text='The new total quantity after the change.')),
                ('reason', models.CharField(blank=True, help_text="The reason for the stock change (e.g., 'Inbound Shipment', 'Sales Order', 'Manual Correction').", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
