# Generated by Django 4.2.23 on 2025-07-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbound', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbounds', to='inbound.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='inbounditem',
            unique_together={('inbound', 'product')},
        ),
    ]
